# Configuration for Simulator_Plebiscito

# General Settings
num_jobs: 20
num_nodes: 50
n_failure: 0
csv_file_path: "traces/pai/"
csv_file: "cleaned_dfws.csv"

# with_bw: false
with_bw: true

# Topology Selection
topology_type: "LeafSpine"

# Topology Settings
LeafSpine:
  num_spine_switches: 2
  num_leaf_switches: 5
  host_per_leaf: 10
  max_spine_capacity: 10000  # Increased from 500 to 10000
  max_leaf_capacity: 10000   # Increased from 500 to 10000
  max_node_bw: 2000         # Increased from 100 to 2000
  max_leaf_to_spine_bw: 2000  # Increased from 100 to 2000

  # Infinite Bandwidth Option
  infinite_bw:
    max_spine_capacity: 99999999999
    max_leaf_capacity: 99999999999
    max_node_bw: 99999999999
    max_leaf_to_spine_bw: 99999999999
  
  # Correctly indented limited_bw section
  limited_bw:
    max_spine_capacity: 10000   # Increased from 500 to 10000
    max_leaf_capacity: 10000    # Increased from 500 to 10000
    max_node_bw: 2000           # Increased from 100 to 2000
    max_leaf_to_spine_bw: 2000  # Increased from 100 to 2000

# Simulation Parameters
utils:
  - "TETRIS"
  - "DRF"
  - "UTIL"
  - "LIKELIHOOD"
  - "SGF"
  - "LGF"
  - "SEQ"
sched:
  - "FIFO"

# Jobs settings
discard_job: false

heterogeneous_nodes: true

fix_duration: true
