# Configuration for Simulator_Plebiscito

# REmember to set the
#  job duration
# output filename

# General Settings
num_jobs: 200
num_nodes: 100
n_failure: 0
csv_file_path: "traces/pai/"
csv_file: "cleaned_dfws.csv"

# Topology Settings
num_spine_switches: 2
num_leaf_switches: 5
host_per_leaf: 10

# Bandwidth Settings

with_bw_options:
  # - true
  - false
  
limited_bw:
  max_spine_capacity: 300
  max_leaf_capacity: 200
  max_node_bw: 20
  max_leaf_to_spine_bw: 100

infinite_bw:
  max_spine_capacity: 99999999999
  max_leaf_capacity: 99999999999
  max_node_bw: 99999999999
  max_leaf_to_spine_bw: 99999999999

# Simulation Parameters
utils:
  - "TETRIS"
  - "DRF"
  - "UTIL"
  - "LIKELIHOOD"
  - "SGF"
  - "LGF"
  - "SEQ"
sched:
  - "FIFO"

# Jobs settings

# discard_job: true
discard_job: false

heterogeneous_nodes: true
# heterogeneous_nodes: false

# fix_duration: true
fix_duration: false
