# Configuration for Simulator_Plebiscito

# REmember to set the
#  job duration
# output filename

# General Settings
num_jobs: 50
num_nodes: 50
n_failure: 0
csv_file_path: "traces/pai/"
csv_file: "cleaned_dfws.csv"


# with_bw: false
with_bw: true

# Topology Selection
topology_type: "LeafSpine"

# Topology Settings
LeafSpine:
  num_spine_switches: 2
  num_leaf_switches: 5
  host_per_leaf: 10
  max_spine_capacity: 500
  max_leaf_capacity: 500
  max_node_bw: 100
  max_leaf_to_spine_bw: 100

  # Infinite Bandwidth Option
  infinite_bw:
    max_spine_capacity: 99999999999
    max_leaf_capacity: 99999999999
    max_node_bw: 99999999999
    max_leaf_to_spine_bw: 99999999999

# Simulation Parameters
utils:
  - "TETRIS"
  - "DRF"
  - "UTIL"
  - "LIKELIHOOD"
  - "SGF"
  - "LGF"
  - "SEQ"
sched:
  - "FIFO"

# Jobs settings

# discard_job: true
discard_job: false

heterogeneous_nodes: true
# heterogeneous_nodes: false

fix_duration: true
# fix_duration: false

topology_type: "FatTree"

FatTree:
  num_core_switches: 2
  num_aggregation_switches: 4
  num_edge_switches: 8
  hosts_per_edge_switch: 10
  core_to_agg_bw: 200
  agg_to_edge_bw: 100
  edge_to_host_bw: 50
