# Configuration for Simulator_Plebiscito

# General Settings

n_failure: 0
csv_file_path: "traces/"
csv_file: "cleaned_dfws.csv"

with_bw: true  # Set to true or false based on your needs

# Topology Selection
topology_type: "FatTree"

num_jobs: 20  # Adjust as needed
# num_nodes will be set based on the topology in main.py

FatTree:
  k: 8  # Must be even; for k=8, number of hosts is (8^3)/4 = 128
  bandwidth: 100  # Bandwidth for all links

  # Infinite Bandwidth Option
  infinite_bw:
    bandwidth: 99999999999

# Simulation Parameters
utils:
  - "TETRIS"
sched:
  - "FIFO"

# Jobs settings
discard_job: false
heterogeneous_nodes: true
fix_duration: false
